"""
This file defines the core semantic model used by ATL: a Concurrent Game Structure.

A Concurrent Game Structure is the standard semantic structure for Alternating-time
Temporal Logic over open systems. Unlike a Kripke structure, where transitions are
already fixed, here every transition is generated by a joint action: each agent chooses
one action, and the combination of all actions determines the next state.

This is the crucial point for ATL:

- CTL reasons about paths in a transition system.
- ATL reasons about strategies of coalitions in a game structure.

So a formula such as:

    <<Controller>> F goal

does not mean "there exists a path to goal".
It means:

    "Controller has a strategy to force goal eventually,
     no matter how the other agents behave."
"""

from itertools import product


class ConcurrentGameStructure:
    """
    Finite Concurrent Game Structure.

    The model contains:
    - states;
    - agents;
    - actions available to each agent in each state;
    - a transition function from state + joint action to next state;
    - a labeling function assigning atomic propositions to states.
    """

    # Initializes an empty concurrent game structure.
    #
    # Input parameters:
    # - none.
    #
    # Return:
    # - nothing.
    def __init__(self):
        self.states = set()
        self.agents = set()
        self.actions = {}
        self.transitions = {}
        self.labels = {}

    # Adds a state to the model.
    #
    # Input parameters:
    # - state: name of the state.
    # - labels: optional collection of atomic propositions true in the state.
    #
    # Return:
    # - nothing.
    def add_state(self, state, labels=None):
        self.states.add(state)
        self.labels[state] = set(labels) if labels is not None else set()

    # Adds an agent to the model.
    #
    # Input parameters:
    # - agent: name of the agent.
    #
    # Return:
    # - nothing.
    def add_agent(self, agent):
        self.agents.add(agent)

    # Defines the actions available to an agent in a state.
    #
    # Input parameters:
    # - state: current state.
    # - agent: selected agent.
    # - actions: collection of action names.
    #
    # Return:
    # - nothing.
    def set_actions(self, state, agent, actions):
        if state not in self.states:
            raise ValueError(f"Unknown state: {state}")

        if agent not in self.agents:
            raise ValueError(f"Unknown agent: {agent}")

        actions = set(actions)

        if not actions:
            raise ValueError("Each agent must have at least one available action")

        self.actions[(state, agent)] = actions

    # Adds one transition generated by a complete joint action.
    #
    # Input parameters:
    # - state: source state.
    # - joint_action: dictionary mapping each agent to one action.
    # - next_state: target state.
    #
    # Return:
    # - nothing.
    def add_transition(self, state, joint_action, next_state):
        if state not in self.states:
            raise ValueError(f"Unknown source state: {state}")

        if next_state not in self.states:
            raise ValueError(f"Unknown target state: {next_state}")

        if set(joint_action.keys()) != self.agents:
            raise ValueError(
                "A transition must specify exactly one action for each agent"
            )

        for agent, action in joint_action.items():
            available_actions = self.get_actions(state, agent)

            if action not in available_actions:
                raise ValueError(
                    f"Action {action} is not available for agent {agent} in state {state}"
                )

        key = (state, self._normalize_joint_action(joint_action))
        self.transitions[key] = next_state

    # Returns the propositions true in a state.
    #
    # Input parameters:
    # - state: selected state.
    #
    # Return:
    # - set of atomic propositions true in the state.
    def get_labels(self, state):
        if state not in self.states:
            raise ValueError(f"Unknown state: {state}")

        return self.labels[state]

    # Returns the available actions of an agent in a state.
    #
    # Input parameters:
    # - state: selected state.
    # - agent: selected agent.
    #
    # Return:
    # - set of available actions.
    def get_actions(self, state, agent):
        if state not in self.states:
            raise ValueError(f"Unknown state: {state}")

        if agent not in self.agents:
            raise ValueError(f"Unknown agent: {agent}")

        key = (state, agent)

        if key not in self.actions:
            raise ValueError(f"No actions defined for agent {agent} in state {state}")

        return self.actions[key]

    # Computes the next state generated by a joint action.
    #
    # Input parameters:
    # - state: current state.
    # - joint_action: dictionary mapping each agent to one action.
    #
    # Return:
    # - successor state.
    def get_next_state(self, state, joint_action):
        key = (state, self._normalize_joint_action(joint_action))

        if key not in self.transitions:
            raise ValueError(
                f"Missing transition from {state} with joint action {joint_action}"
            )

        return self.transitions[key]

    # Generates all possible joint actions for a selected group of agents.
    #
    # Input parameters:
    # - state: current state.
    # - selected_agents: collection of agents.
    #
    # Return:
    # - list of dictionaries mapping each selected agent to one action.
    def get_joint_actions(self, state, selected_agents):
        selected_agents = list(selected_agents)

        if not selected_agents:
            return [{}]

        action_lists = []

        for agent in selected_agents:
            available_actions = sorted(self.get_actions(state, agent))
            action_lists.append(available_actions)

        joint_actions = []

        # A joint action is the Cartesian product of the available actions
        # of all selected agents. This directly represents simultaneous choice.
        for action_tuple in product(*action_lists):
            joint_action = {}

            for index, agent in enumerate(selected_agents):
                joint_action[agent] = action_tuple[index]

            joint_actions.append(joint_action)

        return joint_actions

    # Merges two partial joint actions into a complete joint action.
    #
    # Input parameters:
    # - first: partial joint action.
    # - second: partial joint action.
    #
    # Return:
    # - merged joint action.
    def merge_joint_actions(self, first, second):
        overlapping_agents = set(first.keys()) & set(second.keys())

        if overlapping_agents:
            raise ValueError(f"Joint actions overlap on agents: {overlapping_agents}")

        merged = {}
        merged.update(first)
        merged.update(second)
        return merged

    # Checks whether the transition relation is total.
    #
    # Input parameters:
    # - none.
    #
    # Return:
    # - True if every state and every complete joint action has a successor.
    def is_total(self):
        for state in self.states:
            joint_actions = self.get_joint_actions(state, self.agents)

            for joint_action in joint_actions:
                key = (state, self._normalize_joint_action(joint_action))

                if key not in self.transitions:
                    return False

        return True

    # Raises an error if the model is not total.
    #
    # Input parameters:
    # - none.
    #
    # Return:
    # - nothing.
    def validate_totality(self):
        missing = []

        for state in self.states:
            joint_actions = self.get_joint_actions(state, self.agents)

            for joint_action in joint_actions:
                key = (state, self._normalize_joint_action(joint_action))

                if key not in self.transitions:
                    missing.append((state, joint_action))

        if missing:
            raise ValueError(
                f"The transition relation is not total. Missing: {missing}"
            )

    # Converts a joint action dictionary into a canonical hashable representation.
    #
    # Input parameters:
    # - joint_action: dictionary agent -> action.
    #
    # Return:
    # - sorted tuple of pairs.
    def _normalize_joint_action(self, joint_action):
        return tuple(sorted(joint_action.items()))
